/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.org.recresiduos.telas;

import br.org.recresiduos.entidades.Jogador;
import java.awt.Graphics;
import java.awt.image.BufferedImage;
import javax.swing.ImageIcon;

/**
 *
 * @author Paulo
 */
public class ColetarMaterialCasa extends javax.swing.JDialog {

    /**
     * Creates new form LancaDado
     */
    public ColetarMaterialCasa(java.awt.Frame parent, boolean modal, Jogador jogador) {
        super(parent, modal);
        initComponents();
        
        backBuffer = new BufferedImage(75, 75, BufferedImage.TYPE_INT_RGB);
        bbg = backBuffer.getGraphics();//ISSO TAMBÉM JÁ ESTAVA AQUI...

        ImageIcon dado = new ImageIcon(getClass().getResource("/imagensbir/Dice001.png"));
         bbg.drawImage(dado.getImage(), 500, 100, this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        jLNomeJogador = new javax.swing.JLabel();
        jPMaterialColetado = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLMetal = new javax.swing.JLabel();
        jLPapel = new javax.swing.JLabel();
        jLPlastico = new javax.swing.JLabel();
        jLVidro = new javax.swing.JLabel();
        jLMadeira = new javax.swing.JLabel();
        jLOrganicos = new javax.swing.JLabel();
        jLQtdeOrganicos = new javax.swing.JLabel();
        jLQtdeVidro1 = new javax.swing.JLabel();
        jLQtdeVidro = new javax.swing.JLabel();
        jLQtdePlastico = new javax.swing.JLabel();
        jLQtdePapel = new javax.swing.JLabel();
        jLQtdeMetal = new javax.swing.JLabel();
        jPObjetivo = new javax.swing.JPanel();
        jLObjetivo = new javax.swing.JLabel();
        jBProduzir = new javax.swing.JButton();
        jBReciclar = new javax.swing.JButton();
        jLCartaObjetivo = new javax.swing.JLabel();
        jPColetar = new javax.swing.JPanel();
        jLMaterial = new javax.swing.JLabel();
        jLTipoMaterial = new javax.swing.JLabel();
        jLQtdeMaterial = new javax.swing.JLabel();
        jBDescartar = new javax.swing.JButton();
        jLEscolha = new javax.swing.JLabel();
        jBColetar = new javax.swing.JButton();
        jbContinuarJogando = new javax.swing.JButton();

        jRadioButton1.setText("jRadioButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(0, 102, 102));
        setMaximumSize(new java.awt.Dimension(650, 520));
        setMinimumSize(new java.awt.Dimension(650, 520));
        setName("dialogColetar"); // NOI18N
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(650, 520));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(26, 64, 35));
        jPanel1.setMaximumSize(new java.awt.Dimension(650, 520));
        jPanel1.setMinimumSize(new java.awt.Dimension(650, 520));
        jPanel1.setPreferredSize(new java.awt.Dimension(650, 520));

        jLNomeJogador.setBackground(new java.awt.Color(161, 165, 108));
        jLNomeJogador.setFont(new java.awt.Font("Traditional Arabic", 1, 24)); // NOI18N
        jLNomeJogador.setForeground(new java.awt.Color(26, 64, 35));
        jLNomeJogador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLNomeJogador.setText("Nome Do Jogador");
        jLNomeJogador.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLNomeJogador.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLNomeJogador.setMaximumSize(new java.awt.Dimension(250, 60));
        jLNomeJogador.setMinimumSize(new java.awt.Dimension(250, 60));
        jLNomeJogador.setOpaque(true);
        jLNomeJogador.setPreferredSize(new java.awt.Dimension(250, 60));

        jPMaterialColetado.setBackground(new java.awt.Color(161, 165, 108));
        jPMaterialColetado.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPMaterialColetado.setForeground(new java.awt.Color(26, 64, 35));

        jLabel1.setFont(new java.awt.Font("Traditional Arabic", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(26, 64, 35));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Quantidades Coletadas");

        jLMetal.setBackground(new java.awt.Color(255, 255, 0));
        jLMetal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLMetal.setText("Metal");
        jLMetal.setMaximumSize(new java.awt.Dimension(75, 35));
        jLMetal.setMinimumSize(new java.awt.Dimension(75, 35));
        jLMetal.setName("Metal"); // NOI18N
        jLMetal.setOpaque(true);
        jLMetal.setPreferredSize(new java.awt.Dimension(75, 35));

        jLPapel.setBackground(new java.awt.Color(0, 0, 153));
        jLPapel.setForeground(new java.awt.Color(255, 255, 255));
        jLPapel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLPapel.setText("Papel");
        jLPapel.setMaximumSize(new java.awt.Dimension(75, 35));
        jLPapel.setMinimumSize(new java.awt.Dimension(75, 35));
        jLPapel.setName("Metal"); // NOI18N
        jLPapel.setOpaque(true);
        jLPapel.setPreferredSize(new java.awt.Dimension(75, 35));

        jLPlastico.setBackground(new java.awt.Color(255, 0, 0));
        jLPlastico.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLPlastico.setText("Plástico");
        jLPlastico.setMaximumSize(new java.awt.Dimension(75, 35));
        jLPlastico.setMinimumSize(new java.awt.Dimension(75, 35));
        jLPlastico.setName("Plastico"); // NOI18N
        jLPlastico.setOpaque(true);
        jLPlastico.setPreferredSize(new java.awt.Dimension(75, 35));

        jLVidro.setBackground(new java.awt.Color(51, 153, 0));
        jLVidro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLVidro.setText("Vidro");
        jLVidro.setMaximumSize(new java.awt.Dimension(75, 35));
        jLVidro.setMinimumSize(new java.awt.Dimension(75, 35));
        jLVidro.setName("Vidro"); // NOI18N
        jLVidro.setOpaque(true);
        jLVidro.setPreferredSize(new java.awt.Dimension(75, 35));

        jLMadeira.setBackground(new java.awt.Color(0, 0, 0));
        jLMadeira.setForeground(new java.awt.Color(255, 255, 255));
        jLMadeira.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLMadeira.setText("Madeira");
        jLMadeira.setMaximumSize(new java.awt.Dimension(75, 35));
        jLMadeira.setMinimumSize(new java.awt.Dimension(75, 35));
        jLMadeira.setName("Madeira"); // NOI18N
        jLMadeira.setOpaque(true);
        jLMadeira.setPreferredSize(new java.awt.Dimension(75, 35));

        jLOrganicos.setBackground(new java.awt.Color(153, 102, 0));
        jLOrganicos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLOrganicos.setText("Orgânicos");
        jLOrganicos.setMaximumSize(new java.awt.Dimension(75, 35));
        jLOrganicos.setMinimumSize(new java.awt.Dimension(75, 35));
        jLOrganicos.setName("Organicos"); // NOI18N
        jLOrganicos.setOpaque(true);
        jLOrganicos.setPreferredSize(new java.awt.Dimension(75, 35));

        jLQtdeOrganicos.setBackground(new java.awt.Color(255, 255, 255));
        jLQtdeOrganicos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLQtdeOrganicos.setText("jLabel1");
        jLQtdeOrganicos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLQtdeOrganicos.setMaximumSize(new java.awt.Dimension(50, 35));
        jLQtdeOrganicos.setMinimumSize(new java.awt.Dimension(50, 35));
        jLQtdeOrganicos.setName("QtdeOrganicos"); // NOI18N
        jLQtdeOrganicos.setOpaque(true);
        jLQtdeOrganicos.setPreferredSize(new java.awt.Dimension(50, 35));

        jLQtdeVidro1.setBackground(new java.awt.Color(255, 255, 255));
        jLQtdeVidro1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLQtdeVidro1.setText("jLabel1");
        jLQtdeVidro1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLQtdeVidro1.setMaximumSize(new java.awt.Dimension(50, 35));
        jLQtdeVidro1.setMinimumSize(new java.awt.Dimension(50, 35));
        jLQtdeVidro1.setName("QtdeVidro"); // NOI18N
        jLQtdeVidro1.setOpaque(true);
        jLQtdeVidro1.setPreferredSize(new java.awt.Dimension(50, 35));

        jLQtdeVidro.setBackground(new java.awt.Color(255, 255, 255));
        jLQtdeVidro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLQtdeVidro.setText("jLabel1");
        jLQtdeVidro.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLQtdeVidro.setMaximumSize(new java.awt.Dimension(50, 35));
        jLQtdeVidro.setMinimumSize(new java.awt.Dimension(50, 35));
        jLQtdeVidro.setName("QtdeVidro"); // NOI18N
        jLQtdeVidro.setOpaque(true);
        jLQtdeVidro.setPreferredSize(new java.awt.Dimension(50, 35));

        jLQtdePlastico.setBackground(new java.awt.Color(255, 255, 255));
        jLQtdePlastico.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLQtdePlastico.setText("jLabel1");
        jLQtdePlastico.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLQtdePlastico.setMaximumSize(new java.awt.Dimension(50, 35));
        jLQtdePlastico.setMinimumSize(new java.awt.Dimension(50, 35));
        jLQtdePlastico.setName("QtdePlastico"); // NOI18N
        jLQtdePlastico.setOpaque(true);
        jLQtdePlastico.setPreferredSize(new java.awt.Dimension(50, 35));

        jLQtdePapel.setBackground(new java.awt.Color(255, 255, 255));
        jLQtdePapel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLQtdePapel.setText("jLabel1");
        jLQtdePapel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLQtdePapel.setMaximumSize(new java.awt.Dimension(50, 35));
        jLQtdePapel.setMinimumSize(new java.awt.Dimension(50, 35));
        jLQtdePapel.setName("QtdePapel"); // NOI18N
        jLQtdePapel.setOpaque(true);
        jLQtdePapel.setPreferredSize(new java.awt.Dimension(50, 35));

        jLQtdeMetal.setBackground(new java.awt.Color(255, 255, 255));
        jLQtdeMetal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLQtdeMetal.setText("jLabel1");
        jLQtdeMetal.setMaximumSize(new java.awt.Dimension(50, 35));
        jLQtdeMetal.setMinimumSize(new java.awt.Dimension(50, 35));
        jLQtdeMetal.setName("QtdeMetal"); // NOI18N
        jLQtdeMetal.setOpaque(true);
        jLQtdeMetal.setPreferredSize(new java.awt.Dimension(50, 35));

        javax.swing.GroupLayout jPMaterialColetadoLayout = new javax.swing.GroupLayout(jPMaterialColetado);
        jPMaterialColetado.setLayout(jPMaterialColetadoLayout);
        jPMaterialColetadoLayout.setHorizontalGroup(
            jPMaterialColetadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPMaterialColetadoLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPMaterialColetadoLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPMaterialColetadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPMaterialColetadoLayout.createSequentialGroup()
                        .addComponent(jLMetal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLQtdeMetal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPMaterialColetadoLayout.createSequentialGroup()
                        .addComponent(jLPapel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLQtdePapel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPMaterialColetadoLayout.createSequentialGroup()
                        .addComponent(jLPlastico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLQtdePlastico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPMaterialColetadoLayout.createSequentialGroup()
                        .addComponent(jLVidro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLQtdeVidro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPMaterialColetadoLayout.createSequentialGroup()
                        .addComponent(jLMadeira, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLQtdeVidro1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPMaterialColetadoLayout.createSequentialGroup()
                        .addComponent(jLOrganicos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLQtdeOrganicos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPMaterialColetadoLayout.setVerticalGroup(
            jPMaterialColetadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPMaterialColetadoLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jPMaterialColetadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLMetal, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLQtdeMetal, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPMaterialColetadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLPapel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLQtdePapel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPMaterialColetadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLPlastico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLQtdePlastico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPMaterialColetadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLVidro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLQtdeVidro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPMaterialColetadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLMadeira, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLQtdeVidro1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPMaterialColetadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLOrganicos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLQtdeOrganicos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLMetal.getAccessibleContext().setAccessibleName("Metal");
        jLPlastico.getAccessibleContext().setAccessibleName("Plastico");
        jLOrganicos.getAccessibleContext().setAccessibleName("Organicos");
        jLQtdeOrganicos.getAccessibleContext().setAccessibleName("QtdeOrganicos");
        jLQtdeVidro.getAccessibleContext().setAccessibleName("QtdeVidro");
        jLQtdePlastico.getAccessibleContext().setAccessibleName("QtdePlastico");
        jLQtdePapel.getAccessibleContext().setAccessibleName("QtdePapel");
        jLQtdeMetal.getAccessibleContext().setAccessibleName("QtdeMetal");

        jPObjetivo.setBackground(new java.awt.Color(161, 165, 108));
        jPObjetivo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPObjetivo.setMaximumSize(new java.awt.Dimension(209, 341));
        jPObjetivo.setMinimumSize(new java.awt.Dimension(209, 341));
        jPObjetivo.setName("Objetivo"); // NOI18N
        jPObjetivo.setPreferredSize(new java.awt.Dimension(209, 341));

        jLObjetivo.setFont(new java.awt.Font("Traditional Arabic", 1, 18)); // NOI18N
        jLObjetivo.setForeground(new java.awt.Color(26, 64, 35));
        jLObjetivo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLObjetivo.setText("Seu Objetivo");
        jLObjetivo.setName("Objetivo"); // NOI18N

        jBProduzir.setMnemonic('P');
        jBProduzir.setText("Produzir");
        jBProduzir.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBProduzir.setMaximumSize(new java.awt.Dimension(105, 35));
        jBProduzir.setMinimumSize(new java.awt.Dimension(105, 35));
        jBProduzir.setName("Coletar"); // NOI18N
        jBProduzir.setPreferredSize(new java.awt.Dimension(105, 35));

        jBReciclar.setMnemonic('R');
        jBReciclar.setText("Reciclar");
        jBReciclar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBReciclar.setMaximumSize(new java.awt.Dimension(105, 35));
        jBReciclar.setMinimumSize(new java.awt.Dimension(105, 35));
        jBReciclar.setName("Descartar"); // NOI18N
        jBReciclar.setPreferredSize(new java.awt.Dimension(105, 35));
        jBReciclar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBReciclarActionPerformed(evt);
            }
        });

        jLCartaObjetivo.setBackground(new java.awt.Color(204, 0, 0));
        jLCartaObjetivo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLCartaObjetivo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensbir/CartaObjetivoFrente.png"))); // NOI18N
        jLCartaObjetivo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLCartaObjetivo.setMaximumSize(new java.awt.Dimension(150, 245));
        jLCartaObjetivo.setMinimumSize(new java.awt.Dimension(150, 245));
        jLCartaObjetivo.setName("CartaObjetivo"); // NOI18N
        jLCartaObjetivo.setPreferredSize(new java.awt.Dimension(150, 245));

        javax.swing.GroupLayout jPObjetivoLayout = new javax.swing.GroupLayout(jPObjetivo);
        jPObjetivo.setLayout(jPObjetivoLayout);
        jPObjetivoLayout.setHorizontalGroup(
            jPObjetivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLObjetivo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPObjetivoLayout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addGroup(jPObjetivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPObjetivoLayout.createSequentialGroup()
                        .addGroup(jPObjetivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jBReciclar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBProduzir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPObjetivoLayout.createSequentialGroup()
                        .addComponent(jLCartaObjetivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23))))
        );
        jPObjetivoLayout.setVerticalGroup(
            jPObjetivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPObjetivoLayout.createSequentialGroup()
                .addComponent(jLObjetivo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLCartaObjetivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBProduzir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBReciclar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
        );

        jLObjetivo.getAccessibleContext().setAccessibleName("Objetivo");
        jLCartaObjetivo.getAccessibleContext().setAccessibleName("CartaObjetivo");

        jPColetar.setBackground(new java.awt.Color(161, 165, 108));
        jPColetar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPColetar.setMaximumSize(new java.awt.Dimension(196, 341));
        jPColetar.setMinimumSize(new java.awt.Dimension(196, 341));
        jPColetar.setName("Coletar"); // NOI18N
        jPColetar.setPreferredSize(new java.awt.Dimension(196, 341));

        jLMaterial.setFont(new java.awt.Font("Traditional Arabic", 1, 18)); // NOI18N
        jLMaterial.setForeground(new java.awt.Color(26, 64, 35));
        jLMaterial.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLMaterial.setText("Material Para Coletar");
        jLMaterial.setName("Material"); // NOI18N

        jLTipoMaterial.setBackground(new java.awt.Color(255, 255, 0));
        jLTipoMaterial.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLTipoMaterial.setText("Tipo de Material");
        jLTipoMaterial.setMaximumSize(new java.awt.Dimension(75, 35));
        jLTipoMaterial.setMinimumSize(new java.awt.Dimension(75, 35));
        jLTipoMaterial.setName("TipoMaterial"); // NOI18N
        jLTipoMaterial.setOpaque(true);
        jLTipoMaterial.setPreferredSize(new java.awt.Dimension(75, 35));

        jLQtdeMaterial.setBackground(new java.awt.Color(255, 255, 255));
        jLQtdeMaterial.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLQtdeMaterial.setText("jLabel1");
        jLQtdeMaterial.setMaximumSize(new java.awt.Dimension(75, 35));
        jLQtdeMaterial.setMinimumSize(new java.awt.Dimension(75, 35));
        jLQtdeMaterial.setName("QtdeMaterial"); // NOI18N
        jLQtdeMaterial.setOpaque(true);
        jLQtdeMaterial.setPreferredSize(new java.awt.Dimension(75, 35));

        jBDescartar.setMnemonic('D');
        jBDescartar.setText("Descartar");
        jBDescartar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBDescartar.setMaximumSize(new java.awt.Dimension(105, 35));
        jBDescartar.setMinimumSize(new java.awt.Dimension(105, 35));
        jBDescartar.setName("Descartar"); // NOI18N
        jBDescartar.setPreferredSize(new java.awt.Dimension(105, 35));
        jBDescartar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBDescartarActionPerformed(evt);
            }
        });

        jLEscolha.setFont(new java.awt.Font("Traditional Arabic", 1, 18)); // NOI18N
        jLEscolha.setForeground(new java.awt.Color(26, 64, 35));
        jLEscolha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLEscolha.setText("O que você vai fazer?");
        jLEscolha.setName("Material"); // NOI18N

        jBColetar.setMnemonic('C');
        jBColetar.setText("Coletar");
        jBColetar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBColetar.setMaximumSize(new java.awt.Dimension(105, 35));
        jBColetar.setMinimumSize(new java.awt.Dimension(105, 35));
        jBColetar.setName("Coletar"); // NOI18N
        jBColetar.setPreferredSize(new java.awt.Dimension(105, 35));

        javax.swing.GroupLayout jPColetarLayout = new javax.swing.GroupLayout(jPColetar);
        jPColetar.setLayout(jPColetarLayout);
        jPColetarLayout.setHorizontalGroup(
            jPColetarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLMaterial, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
            .addComponent(jLEscolha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPColetarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPColetarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPColetarLayout.createSequentialGroup()
                        .addGroup(jPColetarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLTipoMaterial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLQtdeMaterial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(57, 57, 57))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPColetarLayout.createSequentialGroup()
                        .addGroup(jPColetarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jBDescartar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBColetar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39))))
        );
        jPColetarLayout.setVerticalGroup(
            jPColetarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPColetarLayout.createSequentialGroup()
                .addComponent(jLMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jLTipoMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLQtdeMaterial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLEscolha, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBColetar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBDescartar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLTipoMaterial.getAccessibleContext().setAccessibleName("TipoMaterial");
        jLQtdeMaterial.getAccessibleContext().setAccessibleName("QtdeMaterial");

        jbContinuarJogando.setMnemonic('J');
        jbContinuarJogando.setText("Continuar Jogando");
        jbContinuarJogando.setActionCommand("ContinuarJogando");
        jbContinuarJogando.setName("ContinuarJogando"); // NOI18N
        jbContinuarJogando.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbContinuarJogandoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLNomeJogador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPObjetivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jbContinuarJogando, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPMaterialColetado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPColetar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLNomeJogador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPMaterialColetado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPObjetivo, javax.swing.GroupLayout.DEFAULT_SIZE, 375, Short.MAX_VALUE)
                    .addComponent(jPColetar, javax.swing.GroupLayout.DEFAULT_SIZE, 375, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbContinuarJogando, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );

        jPObjetivo.getAccessibleContext().setAccessibleName("Objetivo");
        jPColetar.getAccessibleContext().setAccessibleName("Coletar");
        jbContinuarJogando.getAccessibleContext().setAccessibleDescription("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        getAccessibleContext().setAccessibleName("DialogColetar");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBDescartarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBDescartarActionPerformed
        this.dispose();
    }//GEN-LAST:event_jBDescartarActionPerformed

    private void jBReciclarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBReciclarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBReciclarActionPerformed

    private void jbContinuarJogandoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbContinuarJogandoActionPerformed
        this.dispose();
    }//GEN-LAST:event_jbContinuarJogandoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ColetarMaterialCasa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ColetarMaterialCasa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ColetarMaterialCasa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ColetarMaterialCasa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ColetarMaterialCasa dialog = new ColetarMaterialCasa(new javax.swing.JFrame(), true, new Jogador());
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBColetar;
    private javax.swing.JButton jBDescartar;
    private javax.swing.JButton jBProduzir;
    private javax.swing.JButton jBReciclar;
    private javax.swing.JLabel jLCartaObjetivo;
    private javax.swing.JLabel jLEscolha;
    private javax.swing.JLabel jLMadeira;
    private javax.swing.JLabel jLMaterial;
    private javax.swing.JLabel jLMetal;
    private javax.swing.JLabel jLNomeJogador;
    private javax.swing.JLabel jLObjetivo;
    private javax.swing.JLabel jLOrganicos;
    private javax.swing.JLabel jLPapel;
    private javax.swing.JLabel jLPlastico;
    private javax.swing.JLabel jLQtdeMaterial;
    private javax.swing.JLabel jLQtdeMetal;
    private javax.swing.JLabel jLQtdeOrganicos;
    private javax.swing.JLabel jLQtdePapel;
    private javax.swing.JLabel jLQtdePlastico;
    private javax.swing.JLabel jLQtdeVidro;
    private javax.swing.JLabel jLQtdeVidro1;
    private javax.swing.JLabel jLTipoMaterial;
    private javax.swing.JLabel jLVidro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPColetar;
    private javax.swing.JPanel jPMaterialColetado;
    private javax.swing.JPanel jPObjetivo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JButton jbContinuarJogando;
    // End of variables declaration//GEN-END:variables

    private BufferedImage backBuffer;
    private Graphics g = getGraphics(); //ISSO JÁ ESTAVA AQUI
    private Graphics bbg; // = backBuffer.getGraphics();//ISSO TAMBÉM JÁ ESTAVA AQUI...

}
