/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package exemplobancoimobiliario;

import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author Paulo
 */
public class Tabuleiro extends javax.swing.JFrame {

    /**
     * Creates new form Tabuleiro
     */
    public Tabuleiro() {
        initComponents();
        // configura as casas que são usadas no tabuleiro;
        configuraCasasTabuleiro();

        // pode ser mais útil transformar os jogadores em coleção, veremos mais adiante
        j1 = new Jogador("Jogador 1");
        j2 = new Jogador("Jogador 2");

        // já informa no label qual é o jogador que está jogando
        jlJogadorTurno.setText(j1.getNome());

        // inicia os dados do jogo
        rodada = 1;
        branco = 0;
        preto = 0;
        ocupado = 0;
        ocupadoBranco = 0;
        ocupadoPreto = 0;
        saldo1 = 2000.00;
        saldo2 = 2000.00;
        dado = new Dado();
    }

    private void configuraCasasTabuleiro() {
        /*
         Uma coleção de objetos é uma relação de objetos similares entre si, e isso pode facilitar mexer com eles.
         A posição inicial de uma coleção é a posição 0, então, se declararmos uma coleção de casas como tendo 20 
         casas, isso significa que a coleção vai do 0 ao 19. Para facilitar a contagem, prefiro criar a coleção 
         com 21 posições, para ignorar a posição 0, e contar sempre de 1 a 20
         */
        for (int i = 0; i < 21; i++) {
            Casa c;
            // se for número ímpar, a casa pode comprar
            if (i % 2 != 0) {
                c = new Casa(true, 100, 10, 10, 100, i);
            } // se for número par, a casa não pode comprar
            else {
                c = new Casa(false, 100, 10, 10, 100, i);
            }

            // adiciona a casa á coleção
            casas.add(c);
        }

        System.out.println("Foram configuradas " + casas.size() + " casas");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlJogadorTurno = new javax.swing.JLabel();
        jbJogar = new javax.swing.JButton();
        jbComprar = new javax.swing.JButton();
        jlCasa9 = new javax.swing.JLabel();
        jlCasa2 = new javax.swing.JLabel();
        jlCasa11 = new javax.swing.JLabel();
        jlCasa4 = new javax.swing.JLabel();
        jlDadoRolado = new javax.swing.JLabel();
        jlCasa5 = new javax.swing.JLabel();
        jlCasa10 = new javax.swing.JLabel();
        jlCasa7 = new javax.swing.JLabel();
        jlCasa20 = new javax.swing.JLabel();
        jlCasa1 = new javax.swing.JLabel();
        jlCasa6 = new javax.swing.JLabel();
        jlCasa3 = new javax.swing.JLabel();
        jlCasa12 = new javax.swing.JLabel();
        jlCasa13 = new javax.swing.JLabel();
        jlCasa14 = new javax.swing.JLabel();
        jlCasa15 = new javax.swing.JLabel();
        jlCasa16 = new javax.swing.JLabel();
        jlCasa17 = new javax.swing.JLabel();
        jlCasa18 = new javax.swing.JLabel();
        jlCasa19 = new javax.swing.JLabel();
        jlCasa8 = new javax.swing.JLabel();
        jlValorDado = new javax.swing.JLabel();
        jlSaldo = new javax.swing.JLabel();
        jbVender = new javax.swing.JButton();
        jlNumeroCasa = new javax.swing.JLabel();
        jTFNumeroCasa = new javax.swing.JTextField();
        jlComprarVender = new javax.swing.JLabel();
        jTFComprarVender = new javax.swing.JTextField();
        jlValor = new javax.swing.JLabel();
        jTFValor = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlJogadorTurno.setText("Vez do Jogador:");

        jbJogar.setText("Jogar");
        jbJogar.setAutoscrolls(true);
        jbJogar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbJogarActionPerformed(evt);
            }
        });

        jbComprar.setText("Comprar");
        jbComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbComprarActionPerformed(evt);
            }
        });

        jlCasa9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Casa001.png"))); // NOI18N
        jlCasa9.setText("Casa 9");

        jlCasa2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Casa002.png"))); // NOI18N
        jlCasa2.setText("Casa 2");

        jlCasa11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Casa003.png"))); // NOI18N
        jlCasa11.setText("Casa 11");

        jlCasa4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Casa004.png"))); // NOI18N
        jlCasa4.setText("Casa 4");

        jlDadoRolado.setFont(new java.awt.Font("Arial Unicode MS", 0, 18)); // NOI18N
        jlDadoRolado.setForeground(new java.awt.Color(153, 0, 0));

        jlCasa5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Casa001.png"))); // NOI18N
        jlCasa5.setText("Casa 5");

        jlCasa10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Casa002.png"))); // NOI18N
        jlCasa10.setText("Casa 10");

        jlCasa7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Casa003.png"))); // NOI18N
        jlCasa7.setText("Casa 7");

        jlCasa20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Casa004.png"))); // NOI18N
        jlCasa20.setText("Casa 20");

        jlCasa1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Casa001.png"))); // NOI18N
        jlCasa1.setText("Casa 1");

        jlCasa6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Casa002.png"))); // NOI18N
        jlCasa6.setText("Casa 6");

        jlCasa3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Casa003.png"))); // NOI18N
        jlCasa3.setText("Casa 3");

        jlCasa12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Casa004.png"))); // NOI18N
        jlCasa12.setText("Casa 12");

        jlCasa13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Casa001.png"))); // NOI18N
        jlCasa13.setText("Casa 13");

        jlCasa14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Casa002.png"))); // NOI18N
        jlCasa14.setText("Casa 14");

        jlCasa15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Casa003.png"))); // NOI18N
        jlCasa15.setText("Casa 15");

        jlCasa16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Casa004.png"))); // NOI18N
        jlCasa16.setText("Casa 16");

        jlCasa17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Casa001.png"))); // NOI18N
        jlCasa17.setText("Casa 17");

        jlCasa18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Casa002.png"))); // NOI18N
        jlCasa18.setText("Casa 18");

        jlCasa19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Casa003.png"))); // NOI18N
        jlCasa19.setText("Casa 19");

        jlCasa8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Casa004.png"))); // NOI18N
        jlCasa8.setText("Casa 8");

        jlValorDado.setFont(new java.awt.Font("Arial Unicode MS", 1, 14)); // NOI18N
        jlValorDado.setText("Valor do Dado:");

        jlSaldo.setText("Saldo:");

        jbVender.setText("Vender");
        jbVender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbVenderActionPerformed(evt);
            }
        });

        jlNumeroCasa.setText("Número Casa:");

        jTFNumeroCasa.setEditable(false);

        jlComprarVender.setText("Comprar/Vender:");

        jTFComprarVender.setEditable(false);

        jlValor.setText("Valor:");

        jTFValor.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlCasa20, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlValorDado)
                        .addGap(10, 10, 10)
                        .addComponent(jlDadoRolado))
                    .addComponent(jlCasa19, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlJogadorTurno)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlCasa1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jlCasa2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jlCasa3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jlCasa4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jlSaldo)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbJogar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbComprar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbVender)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlNumeroCasa)
                                    .addComponent(jlComprarVender)
                                    .addComponent(jlValor))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTFNumeroCasa, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                                    .addComponent(jTFComprarVender)
                                    .addComponent(jTFValor)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlCasa5, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jlCasa6, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jlCasa7, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jlCasa9, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jlCasa10, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jlCasa8, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jlCasa13, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jlCasa12, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jlCasa11, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlCasa18, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlCasa17, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlCasa16, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlCasa15, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlCasa14, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlJogadorTurno)
                    .addComponent(jlNumeroCasa)
                    .addComponent(jTFNumeroCasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlComprarVender)
                            .addComponent(jTFComprarVender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlValor)
                            .addComponent(jTFValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlSaldo)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbJogar)
                            .addComponent(jbComprar)
                            .addComponent(jbVender))))
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlCasa2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlCasa4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlCasa5, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlCasa7, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlCasa1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlCasa6, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlCasa3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlCasa8, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlCasa9, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlCasa20, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlDadoRolado)
                    .addComponent(jlValorDado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlCasa10, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlCasa19, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlCasa11, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlCasa16, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlCasa17, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlCasa18, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlCasa15, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlCasa14, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlCasa13, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlCasa12, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jlDadoRolado.getAccessibleContext().setAccessibleDescription("");
        jbVender.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbJogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbJogarActionPerformed

        if (rodada % 2 != 0) {
            jogadorVez = j1;
        } else {
            jogadorVez = j2;
        }

        int casasAndar = dado.rolarDados();
        jlDadoRolado.setText(String.valueOf(casasAndar));
        jlJogadorTurno.setText(jogadorVez.getNome());
        jlSaldo.setText(String.valueOf(jogadorVez.getSaldo()));
        jlJogadorTurno.updateUI();

        for (int i = 1; i <= casasAndar; i++) {
//            if (jogadorVez.getNumeroCasa() == 20) {
            if (jogadorVez.getNumeroCasa() >= 20) {
                jogadorVez.setNumeroCasa(1);
                ocupado = jogadorVez.getNumeroCasa();
                break; // se voltou ao início, pode sair do loop
            } else {
                jogadorVez.setNumeroCasa(jogadorVez.getNumeroCasa() + 1);
                ocupado = jogadorVez.getNumeroCasa();
            }

        }

        // mostra as informações da casa ocupada
        Casa c = casas.get(ocupado);
        jTFNumeroCasa.setText(String.valueOf(c.getNumeroCasa()));
        jTFValor.setText(String.valueOf(c.getAluguel()));
        if (c.isPodeComprar()) {
            jTFComprarVender.setText("VENDER");
        } else {
            jTFComprarVender.setText("COMPRAR");
        }

        if (jogadorVez == j1) {

            switch (ocupadoBranco) {
                case 1:
                    if (preto == 1) {
                        jlCasa1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Casa001_Ocupada_Preto.png")));
                    } else {
                        jlCasa1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Casa001.png")));
                    }
                    break;
                case 2:
                    if (preto == 2) {
                        jlCasa2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Casa002_Ocupada_Preto.png")));
                    } else {
                        jlCasa2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Casa002.png")));
                    }
                    break;
                case 3:
                    if (preto == 3) {
                        jlCasa3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Casa003_Ocupada_Preto.png")));
                    } else {
                        jlCasa3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Casa003.png")));
                    }
                    break;
                case 4:
                    if (preto == 4) {
                        jlCasa4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Casa004_Ocupada_Preto.png")));
                    } else {
                        jlCasa4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Casa004.png")));
                    }
                    break;
                case 5:
                    if (preto == 5) {
                        jlCasa5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Casa001_Ocupada_Preto.png")));
                    } else {
                        jlCasa5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Casa001.png")));
                    }
                    break;
                case 6:
                    if (preto == 6) {
                        jlCasa6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Casa002_Ocupada_Preto.png")));
                    } else {
                        jlCasa6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Casa002.png")));
                    }
                    break;
                case 7:
                    if (preto == 7) {
                        jlCasa7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Casa003_Ocupada_Preto.png")));
                    } else {
                        jlCasa7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Casa003.png")));
                    }
                    break;
                case 8:
                    if (preto == 8) {
                        jlCasa8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Casa004_Ocupada_Preto.png")));
                    } else {
                        jlCasa8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Casa004.png")));
                    }
                    break;
                case 9:
                    if (preto == 9) {
                        jlCasa9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Casa001_Ocupada_Preto.png")));
                    } else {
                        jlCasa9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Casa001.png")));
                    }
                    break;
                case 10:
                    if (preto == 10) {
                        jlCasa10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Casa002_Ocupada_Preto.png")));
                    } else {
                        jlCasa10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Casa002.png")));
                    }
                    break;
                case 11:
                    if (preto == 11) {
                        jlCasa11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Casa003_Ocupada_Preto.png")));
                    } else {
                        jlCasa11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Casa003.png")));
                    }
                    break;
                case 12:
                    if (preto == 12) {
                        jlCasa12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Casa004_Ocupada_Preto.png")));
                    } else {
                        jlCasa12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Casa004.png")));
                    }
                    break;
                case 13:
                    if (preto == 13) {
                        jlCasa13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Casa001_Ocupada_Preto.png")));
                    } else {
                        jlCasa13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Casa001.png")));
                    }
                    break;
                case 14:
                    if (preto == 14) {
                        jlCasa14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Casa002_Ocupada_Preto.png")));
                    } else {
                        jlCasa14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Casa002.png")));
                    }
                    break;
                case 15:
                    if (preto == 15) {
                        jlCasa15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Casa003_Ocupada_Preto.png")));
                    } else {
                        jlCasa15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Casa003.png")));
                    }
                    break;
                case 16:
                    if (preto == 16) {
                        jlCasa16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Casa004_Ocupada_Preto.png")));
                    } else {
                        jlCasa16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Casa004.png")));
                    }
                    break;
                case 17:
                    if (preto == 17) {
                        jlCasa17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Casa001_Ocupada_Preto.png")));
                    } else {
                        jlCasa17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Casa001.png")));
                    }
                    break;
                case 18:
                    if (preto == 18) {
                        jlCasa18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Casa002_Ocupada_Preto.png")));
                    } else {
                        jlCasa18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Casa002.png")));
                    }
                    break;
                case 19:
                    if (preto == 19) {
                        jlCasa19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Casa003_Ocupada_Preto.png")));
                    } else {
                        jlCasa19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Casa003.png")));
                    }
                    break;
                case 20:
                    if (preto == 20) {
                        jlCasa20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Casa004_Ocupada_Preto.png")));
                    } else {
                        jlCasa20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Casa004.png")));
                    }
                    break;

            }
            ocupadoBranco = ocupado;

            switch (jogadorVez.getNumeroCasa()) {
                case 1:
                    if (preto == 1) {
                        jlCasa1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Casa001_Ocupada_Dois.png")));
                    } else {
                        jlCasa1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Casa001_Ocupada_Branco.png")));
                    }
                    branco = 1;
                    break;
                case 2:
                    if (preto == 2) {
                        jlCasa2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Casa002_Ocupada_Dois.png")));
                    } else {
                        jlCasa2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Casa002_Ocupada_Branco.png")));
                    }
                    branco = 2;
                    break;
                case 3:
                    if (preto == 3) {
                        jlCasa3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Casa003_Ocupada_Dois.png")));
                    } else {
                        jlCasa3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Casa003_Ocupada_Branco.png")));
                    }
                    branco = 3;
                    break;
                case 4:
                    if (preto == 4) {
                        jlCasa4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Casa004_Ocupada_Dois.png")));
                    } else {
                        jlCasa4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Casa004_Ocupada_Branco.png")));
                    }
                    branco = 4;
                    break;
                case 5:
                    if (preto == 5) {
                        jlCasa5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Casa001_Ocupada_Dois.png")));
                    } else {
                        jlCasa5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Casa001_Ocupada_Branco.png")));
                    }
                    branco = 5;
                    break;
                case 6:
                    if (preto == 6) {
                        jlCasa6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Casa002_Ocupada_Dois.png")));
                    } else {
                        jlCasa6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Casa002_Ocupada_Branco.png")));
                    }
                    branco = 6;
                    break;
                case 7:
                    if (preto == 7) {
                        jlCasa7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Casa003_Ocupada_Dois.png")));
                    } else {
                        jlCasa7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Casa003_Ocupada_Branco.png")));
                    }
                    branco = 7;
                    break;
                case 8:
                    if (preto == 8) {
                        jlCasa8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Casa004_Ocupada_Dois.png")));
                    } else {
                        jlCasa8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Casa004_Ocupada_Branco.png")));
                    }
                    branco = 8;
                    break;
                case 9:
                    if (preto == 9) {
                        jlCasa9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Casa001_Ocupada_Dois.png")));
                    } else {
                        jlCasa9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Casa001_Ocupada_Branco.png")));
                    }
                    branco = 9;
                    break;
                case 10:
                    if (preto == 10) {
                        jlCasa10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Casa002_Ocupada_Dois.png")));
                    } else {
                        jlCasa10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Casa002_Ocupada_Branco.png")));
                    }
                    branco = 10;
                    break;
                case 11:
                    if (preto == 11) {
                        jlCasa11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Casa003_Ocupada_Dois.png")));
                    } else {
                        jlCasa11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Casa003_Ocupada_Branco.png")));
                    }
                    branco = 11;
                    break;
                case 12:
                    if (preto == 12) {
                        jlCasa12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Casa004_Ocupada_Dois.png")));
                    } else {
                        jlCasa12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Casa004_Ocupada_Branco.png")));
                    }
                    branco = 12;
                    break;
                case 13:
                    if (preto == 13) {
                        jlCasa13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Casa001_Ocupada_Dois.png")));
                    } else {
                        jlCasa13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Casa001_Ocupada_Branco.png")));
                    }
                    branco = 13;
                    break;
                case 14:
                    if (preto == 14) {
                        jlCasa14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Casa002_Ocupada_Dois.png")));
                    } else {
                        jlCasa14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Casa002_Ocupada_Branco.png")));
                    }
                    branco = 14;
                    break;
                case 15:
                    if (preto == 15) {
                        jlCasa15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Casa003_Ocupada_Dois.png")));
                    } else {
                        jlCasa15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Casa003_Ocupada_Branco.png")));
                    }
                    branco = 15;
                    break;
                case 16:
                    if (preto == 16) {
                        jlCasa16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Casa004_Ocupada_Dois.png")));
                    } else {
                        jlCasa16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Casa004_Ocupada_Branco.png")));
                    }
                    branco = 16;
                    break;
                case 17:
                    if (preto == 17) {
                        jlCasa17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Casa001_Ocupada_Dois.png")));
                    } else {
                        jlCasa17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Casa001_Ocupada_Branco.png")));
                    }
                    branco = 17;
                    break;
                case 18:
                    if (preto == 18) {
                        jlCasa18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Casa002_Ocupada_Dois.png")));
                    } else {
                        jlCasa18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Casa002_Ocupada_Branco.png")));
                    }
                    branco = 18;
                    break;
                case 19:
                    if (preto == 19) {
                        jlCasa19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Casa003_Ocupada_Dois.png")));
                    } else {
                        jlCasa19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Casa003_Ocupada_Branco.png")));
                    }
                    branco = 19;
                    break;
                case 20:
                    if (preto == 20) {
                        jlCasa20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Casa004_Ocupada_Dois.png")));
                    } else {
                        jlCasa20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Casa004_Ocupada_Branco.png")));
                    }
                    branco = 20;
                    break;
            }

        } else {

            switch (ocupadoPreto) {

                case 1:
                    if (branco == 1) {
                        jlCasa1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Casa001_Ocupada_Branco.png")));
                    } else {
                        jlCasa1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Casa001.png")));
                    }
                    break;
                case 2:
                    if (branco == 2) {
                        jlCasa2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Casa002_Ocupada_Branco.png")));
                    } else {
                        jlCasa2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Casa002.png")));
                    }
                    break;
                case 3:
                    if (branco == 3) {
                        jlCasa3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Casa003_Ocupada_Branco.png")));
                    } else {
                        jlCasa3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Casa003.png")));
                    }
                    break;
                case 4:
                    if (branco == 4) {
                        jlCasa4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Casa004_Ocupada_Branco.png")));
                    } else {
                        jlCasa4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Casa004.png")));
                    }
                    break;
                case 5:
                    if (branco == 5) {
                        jlCasa5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Casa001_Ocupada_Branco.png")));
                    } else {
                        jlCasa5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Casa001.png")));
                    }
                    break;
                case 6:
                    if (branco == 6) {
                        jlCasa6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Casa002_Ocupada_Branco.png")));
                    } else {
                        jlCasa6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Casa002.png")));
                    }
                    break;
                case 7:
                    if (branco == 7) {
                        jlCasa7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Casa003_Ocupada_Branco.png")));
                    } else {
                        jlCasa7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Casa003.png")));
                    }
                    break;
                case 8:
                    if (branco == 8) {
                        jlCasa8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Casa004_Ocupada_Branco.png")));
                    } else {
                        jlCasa8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Casa004.png")));
                    }
                    break;
                case 9:
                    if (branco == 9) {
                        jlCasa9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Casa001_Ocupada_Branco.png")));
                    } else {
                        jlCasa9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Casa001.png")));
                    }
                    break;
                case 10:
                    if (branco == 10) {
                        jlCasa10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Casa002_Ocupada_Branco.png")));
                    } else {
                        jlCasa10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Casa002.png")));
                    }
                    break;
                case 11:
                    if (branco == 11) {
                        jlCasa11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Casa003_Ocupada_Branco.png")));
                    } else {
                        jlCasa11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Casa003.png")));
                    }
                    break;
                case 12:
                    if (branco == 12) {
                        jlCasa12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Casa004_Ocupada_Branco.png")));
                    } else {
                        jlCasa12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Casa004.png")));
                    }
                    break;
                case 13:
                    if (branco == 13) {
                        jlCasa13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Casa001_Ocupada_Branco.png")));
                    } else {
                        jlCasa13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Casa001.png")));
                    }
                    break;
                case 14:
                    if (branco == 14) {
                        jlCasa14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Casa002_Ocupada_Branco.png")));
                    } else {
                        jlCasa14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Casa002.png")));
                    }
                    break;
                case 15:
                    if (branco == 15) {
                        jlCasa15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Casa003_Ocupada_Branco.png")));
                    } else {
                        jlCasa15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Casa003.png")));
                    }
                    break;
                case 16:
                    if (branco == 16) {
                        jlCasa16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Casa004_Ocupada_Branco.png")));
                    } else {
                        jlCasa16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Casa004.png")));
                    }
                    break;
                case 17:
                    if (branco == 17) {
                        jlCasa17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Casa001_Ocupada_Branco.png")));
                    } else {
                        jlCasa17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Casa001.png")));
                    }
                    break;
                case 18:
                    if (branco == 18) {
                        jlCasa18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Casa002_Ocupada_Branco.png")));
                    } else {
                        jlCasa18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Casa002.png")));
                    }
                    break;
                case 19:
                    if (branco == 19) {
                        jlCasa19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Casa003_Ocupada_Branco.png")));
                    } else {
                        jlCasa19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Casa003.png")));
                    }
                    break;
                case 20:
                    if (branco == 20) {
                        jlCasa20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Casa004_Ocupada_Branco.png")));
                    } else {
                        jlCasa20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Casa004.png")));
                    }
                    break;

            }

            ocupadoPreto = ocupado;
            switch (jogadorVez.getNumeroCasa()) {
                case 1:
                    if (branco == 1) {
                        jlCasa1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Casa001_Ocupada_Dois.png")));
                    } else {
                        jlCasa1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Casa001_Ocupada_Preto.png")));
                    }
                    preto = 1;
                    break;
                case 2:
                    if (branco == 2) {
                        jlCasa2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Casa002_Ocupada_Dois.png")));
                    } else {
                        jlCasa2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Casa002_Ocupada_Preto.png")));
                    }
                    preto = 2;
                    break;
                case 3:
                    if (branco == 3) {
                        jlCasa3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Casa003_Ocupada_Dois.png")));
                    } else {
                        jlCasa3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Casa003_Ocupada_Preto.png")));
                    }
                    preto = 3;
                    break;
                case 4:
                    if (branco == 4) {
                        jlCasa4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Casa004_Ocupada_Dois.png")));
                    } else {
                        jlCasa4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Casa004_Ocupada_Preto.png")));
                    }
                    preto = 4;
                    break;
                case 5:
                    if (branco == 5) {
                        jlCasa5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Casa001_Ocupada_Dois.png")));
                    } else {
                        jlCasa5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Casa001_Ocupada_Preto.png")));
                    }
                    preto = 5;
                    break;
                case 6:
                    if (branco == 6) {
                        jlCasa6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Casa002_Ocupada_Dois.png")));
                    } else {
                        jlCasa6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Casa002_Ocupada_Preto.png")));
                    }
                    preto = 6;
                    break;
                case 7:
                    if (branco == 7) {
                        jlCasa7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Casa003_Ocupada_Dois.png")));
                    } else {
                        jlCasa7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Casa003_Ocupada_Preto.png")));
                    }
                    preto = 7;
                    break;
                case 8:
                    if (branco == 8) {
                        jlCasa8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Casa004_Ocupada_Dois.png")));
                    } else {
                        jlCasa8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Casa004_Ocupada_Preto.png")));
                    }
                    preto = 8;
                    break;
                case 9:
                    if (branco == 9) {
                        jlCasa9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Casa001_Ocupada_Dois.png")));
                    } else {
                        jlCasa9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Casa001_Ocupada_Preto.png")));
                    }
                    preto = 9;
                    break;
                case 10:
                    if (branco == 10) {
                        jlCasa10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Casa002_Ocupada_Dois.png")));
                    } else {
                        jlCasa10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Casa002_Ocupada_Preto.png")));
                    }
                    preto = 10;
                    break;
                case 11:
                    if (branco == 11) {
                        jlCasa11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Casa003_Ocupada_Dois.png")));
                    } else {
                        jlCasa11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Casa003_Ocupada_Preto.png")));
                    }
                    preto = 11;
                    break;
                case 12:
                    if (branco == 12) {
                        jlCasa12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Casa004_Ocupada_Dois.png")));
                    } else {
                        jlCasa12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Casa004_Ocupada_Preto.png")));
                    }
                    preto = 12;
                    break;
                case 13:
                    if (branco == 13) {
                        jlCasa13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Casa001_Ocupada_Dois.png")));
                    } else {
                        jlCasa13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Casa001_Ocupada_Preto.png")));
                    }
                    preto = 13;
                    break;
                case 14:
                    if (branco == 14) {
                        jlCasa14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Casa002_Ocupada_Dois.png")));
                    } else {
                        jlCasa14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Casa002_Ocupada_Preto.png")));
                    }
                    preto = 14;
                    break;
                case 15:
                    if (branco == 15) {
                        jlCasa15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Casa003_Ocupada_Dois.png")));
                    } else {
                        jlCasa15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Casa003_Ocupada_Preto.png")));
                    }
                    preto = 15;
                    break;
                case 16:
                    if (branco == 16) {
                        jlCasa16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Casa004_Ocupada_Dois.png")));
                    } else {
                        jlCasa16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Casa004_Ocupada_Preto.png")));
                    }
                    preto = 16;
                    break;
                case 17:
                    if (branco == 17) {
                        jlCasa17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Casa001_Ocupada_Dois.png")));
                    } else {
                        jlCasa17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Casa001_Ocupada_Preto.png")));
                    }
                    preto = 17;
                    break;
                case 18:
                    if (branco == 18) {
                        jlCasa18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Casa002_Ocupada_Dois.png")));
                    } else {
                        jlCasa18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Casa002_Ocupada_Preto.png")));
                    }
                    preto = 18;
                    break;
                case 19:
                    if (branco == 19) {
                        jlCasa19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Casa003_Ocupada_Dois.png")));
                    } else {
                        jlCasa19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Casa003_Ocupada_Preto.png")));
                    }
                    preto = 19;
                    break;
                case 20:
                    if (branco == 20) {
                        jlCasa20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Casa004_Ocupada_Dois.png")));
                    } else {
                        jlCasa20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Casa004_Ocupada_Preto.png")));
                    }
                    preto = 20;
                    break;
            }
            saldo2 = jogadorVez.getSaldo();
        }

        rodada++;


    }//GEN-LAST:event_jbJogarActionPerformed

    private void jbComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbComprarActionPerformed
//      Jogador jogadorVez = new Jogador();

/*
        if (rodada % 2 != 0) {
//            jlJogadorTurno.setText("Jogador 1");
//            jlSaldo.setText(String.valueOf(saldo1));
            jogadorVez = j1;
//            jlJogadorTurno.updateUI();
        } else {
//            jlJogadorTurno.setText("Jogador 2");
//            jlSaldo.setText(String.valueOf(saldo2));
            jogadorVez = j2;
//            jlJogadorTurno.updateUI();
        }
*/
        // atualiza a interface de usuário com o jogador que está jogando
        jlJogadorTurno.setText(jogadorVez.getNome());
        
        
        // lê o número da casa em que o jogador se encontra
        int numeroCasa = jogadorVez.getNumeroCasa();
        // lê o valor da compra que a casa possui
        double valorCompra = casas.get(numeroCasa).getCompra();
        // atualiza o saldo do jogador
        jogadorVez.setSaldo((jogadorVez.getSaldo()-valorCompra));
        
        System.out.println("O saldo do jogador " + jogadorVez.getNome() + " foi atualizado para " + jogadorVez.getSaldo());
        
        // atualiza a interface de usuário com as informações atualizadas
        jlSaldo.setText(String.valueOf(jogadorVez.getSaldo()));
        jlJogadorTurno.updateUI();
        
/*        
        if (jogadorVez == j1) {

//        casa.setValorCasa(jogadorVez.getNumeroCasa());
//	jogadorVez.setSaldo(jogadorVez.getSaldo()-casa.getValorCasa());            
            saldo1 = jogadorVez.getSaldo();
        } else {
//        casa.setValorCasa(jogadorVez.getNumeroCasa());
//	jogadorVez.setSaldo(jogadorVez.getSaldo()-casa.getValorCasa());

            saldo2 = jogadorVez.getSaldo();
        }
*/        
        
    }//GEN-LAST:event_jbComprarActionPerformed

    private void jbVenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbVenderActionPerformed
        Jogador jogadorVez = new Jogador();
//    Casas casa = new Casas();

        if (rodada % 2 != 0) {
            jlJogadorTurno.setText("Jogador 1");
            jlSaldo.setText(String.valueOf(saldo1));
            jogadorVez = j1;
            jlJogadorTurno.updateUI();
        } else {
            jlJogadorTurno.setText("Jogador 2");
            jlSaldo.setText(String.valueOf(saldo2));
            jogadorVez = j2;
            jlJogadorTurno.updateUI();
        }

        if (jogadorVez == j1) {

//        casa.setValorCasa(jogadorVez.getNumeroCasa());
//	jogadorVez.setSaldo(jogadorVez.getSaldo()+casa.getValorCasa());            
            saldo1 = jogadorVez.getSaldo();
        } else {
//        casa.setValorCasa(jogadorVez.getNumeroCasa());
//	jogadorVez.setSaldo(jogadorVez.getSaldo()+casa.getValorCasa());

            saldo2 = jogadorVez.getSaldo();

        }
    }//GEN-LAST:event_jbVenderActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tabuleiro.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tabuleiro.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tabuleiro.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tabuleiro.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tabuleiro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField jTFComprarVender;
    private javax.swing.JTextField jTFNumeroCasa;
    private javax.swing.JTextField jTFValor;
    private javax.swing.JButton jbComprar;
    private javax.swing.JButton jbJogar;
    private javax.swing.JButton jbVender;
    private javax.swing.JLabel jlCasa1;
    private javax.swing.JLabel jlCasa10;
    private javax.swing.JLabel jlCasa11;
    private javax.swing.JLabel jlCasa12;
    private javax.swing.JLabel jlCasa13;
    private javax.swing.JLabel jlCasa14;
    private javax.swing.JLabel jlCasa15;
    private javax.swing.JLabel jlCasa16;
    private javax.swing.JLabel jlCasa17;
    private javax.swing.JLabel jlCasa18;
    private javax.swing.JLabel jlCasa19;
    private javax.swing.JLabel jlCasa2;
    private javax.swing.JLabel jlCasa20;
    private javax.swing.JLabel jlCasa3;
    private javax.swing.JLabel jlCasa4;
    private javax.swing.JLabel jlCasa5;
    private javax.swing.JLabel jlCasa6;
    private javax.swing.JLabel jlCasa7;
    private javax.swing.JLabel jlCasa8;
    private javax.swing.JLabel jlCasa9;
    private javax.swing.JLabel jlComprarVender;
    private javax.swing.JLabel jlDadoRolado;
    private javax.swing.JLabel jlJogadorTurno;
    private javax.swing.JLabel jlNumeroCasa;
    private javax.swing.JLabel jlSaldo;
    private javax.swing.JLabel jlValor;
    private javax.swing.JLabel jlValorDado;
    // End of variables declaration//GEN-END:variables
    private Jogador j1, j2;
    private Dado dado;
    private int rodada, branco, preto, ocupado, ocupadoBranco, ocupadoPreto;
    private double saldo1, saldo2;

    // declaração da relação de todas as casas que existem no tabuleiro
    private List<Casa> casas = new ArrayList<Casa>();
    // cria uma variável global, para verificar qual é o jogador que está jogando
    private Jogador jogadorVez;
}
